package com.github.belhe001.myWebMiner.myConstants;

import java.util.HashSet;
import java.util.regex.Pattern;

public class my{

	public static HashSet<String> countries = new HashSet<String>();
	public static String sqlhost="localhost";
	public static String sqldb="jscoe";
	public static String sqltable="career";
	public static String sqluser="root";
	public static String sqlpwd="";
	public static String mongohost="localhost";
	public static String mongodb="jscoe";
	public static String mongocoll="career";
	public static int mongodbport=27017;
	public static int timeout = 10*60000;
	public static String useragent = "Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6";
	public static Pattern REmail = Pattern.compile("[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})");
	public static Pattern REtel = Pattern.compile("(\\w{3,8}:)\\s?\\+?\\d{0,4}[\\s.-]*(\\(?\\d{0,4}\\)?)?[\\s.-]*\\d{3,4}[\\s.-]*\\d{3,4}");
	public static String dir="G:\\myTESTbot";
	public static int count=0;
	public static String phantomjspath = "G:\\myTESTbot\\phantomjs.exe";//http://phantomjs.org/download.html

	public my(){
		countries();
	}
	private void countries() {
		countries.add("afghanistan");
		countries.add("albania");
		countries.add("algeria");
		countries.add("angola");
		countries.add("argentina");
		countries.add("armenia");
		countries.add("andorra");
		countries.add("australia");
		countries.add("austria");
		countries.add("azerbaijan");
		countries.add("bahamas");
		countries.add("bahrain");
		countries.add("bangladesh");
		countries.add("barbados");
		countries.add("belarus");
		countries.add("belgium");
		countries.add("belize");
		countries.add("benin");
		countries.add("bhutan");
		countries.add("bolivia");
		countries.add("botswana");
		countries.add("brazil");
		countries.add("brunei");
		countries.add("bulgaria");
		countries.add("burundi");
		countries.add("cambodia");
		countries.add("cameroon");
		countries.add("canada");
		countries.add("chad");
		countries.add("chile");
		countries.add("china");
		countries.add("colombia");
		countries.add("comoros");
		countries.add("croatia");
		countries.add("cuba");
		countries.add("cyprus");
		countries.add("denmark");
		countries.add("djibouti");
		countries.add("dominica");
		countries.add("ecuador");
		countries.add("egypt");
		countries.add("eritrea");
		countries.add("estonia");
		countries.add("ethiopia");
		countries.add("fiji");
		countries.add("finland");
		countries.add("france");
		countries.add("gabon");
		countries.add("gambia");
		countries.add("georgia");
		countries.add("germany");
		countries.add("ghana");
		countries.add("greece");
		countries.add("grenada");
		countries.add("guatemala");
		countries.add("guinea");
		countries.add("guyana");
		countries.add("haiti");
		countries.add("honduras");
		countries.add("hungary");
		countries.add("iceland");
		countries.add("india");
		countries.add("indonesia");
		countries.add("iran");
		countries.add("iraq");
		countries.add("ireland");
		countries.add("israel");
		countries.add("italy");
		countries.add("jamaica");
		countries.add("japan");
		countries.add("jordan");
		countries.add("kazakhstan");
		countries.add("kenya");
		countries.add("kiribati");
		countries.add("kosovo");
		countries.add("kuwait");
		countries.add("kyrgyzstan");
		countries.add("laos");
		countries.add("latvia");
		countries.add("lebanon");
		countries.add("lesotho");
		countries.add("liberia");
		countries.add("libya");
		countries.add("liechtenstein");
		countries.add("lithuania");
		countries.add("luxembourg");
		countries.add("macedonia");
		countries.add("madagascar");
		countries.add("malawi");
		countries.add("malaysia");
		countries.add("maldives");
		countries.add("mali");
		countries.add("malta");
		countries.add("mauritania");
		countries.add("mauritius");
		countries.add("mexico");
		countries.add("micronesia");
		countries.add("moldova"); 
		countries.add("monaco");
		countries.add("mongolia");
		countries.add("montenegro");
		countries.add("morocco");
		countries.add("mozambique");
		countries.add("namibia");
		countries.add("nauru");
		countries.add("nepal");
		countries.add("netherlands");
		countries.add("nicaragua");
		countries.add("niger");
		countries.add("nigeria");
		countries.add("norway");
		countries.add("oman");
		countries.add("pakistan");
		countries.add("palau");
		countries.add("palestine");
		countries.add("panama");
		countries.add("paraguay");
		countries.add("peru");
		countries.add("philippines");
		countries.add("poland");
		countries.add("portugal");
		countries.add("qatar");
		countries.add("romania");
		countries.add("russia");
		countries.add("rwanda");
		countries.add("samoa");
		countries.add("senegal");
		countries.add("serbia");
		countries.add("seychelles");
		countries.add("singapore");
		countries.add("slovakia");
		countries.add("slovenia");
		countries.add("somalia");
		countries.add("spain");
		countries.add("sudan");
		countries.add("suriname");
		countries.add("swaziland");
		countries.add("sweden");
		countries.add("switzerland");
		countries.add("syria");
		countries.add("taiwan");
		countries.add("tajikistan");
		countries.add("tanzania");
		countries.add("thailand");
		countries.add("togo");
		countries.add("tonga");
		countries.add("tunisia");
		countries.add("turkey");
		countries.add("turkmenistan");
		countries.add("tuvalu");
		countries.add("uganda");
		countries.add("ukraine"); 
		countries.add("uruguay");
		countries.add("uzbekistan");
		countries.add("vanuatu");
		countries.add("venezuela");
		countries.add("vietnam");
		countries.add("yemen");
		countries.add("zambia");
		countries.add("zimbabwe");
		countries.add("america");
		/*__------countries which contain spaces--------*/      
		countries.add("Vatican City");
		countries.add("United Arab Emirates");
		countries.add("Trinidad and Tobago");
		countries.add("Timor-Leste");
		countries.add("Timor Leste");
		countries.add("South Sudan");
		countries.add("South Korea");
		countries.add("South Africa");
		countries.add("Solomon Islands");
		countries.add("Sierra Leone");
		countries.add("Saudi Arabia");
		countries.add("Sao Tome and Principe");
		countries.add("San Marino");
		countries.add("St. Vincent and The Grenadines");
		countries.add("Saint Vincent and The Grenadines");
		countries.add("St. Lucia");
		countries.add("Saint Lucia");
		countries.add("St. Kitts and Nevis");
		countries.add("Saint Kitts and Nevis");
		countries.add("Papua New Guinea");
		countries.add("North Korea");
		countries.add("New Zealand");
		countries.add("Myanmar");
		countries.add("Burma");
		countries.add("Marshall Island");
		countries.add("Marshall Islands");
		countries.add("Guinea-Bissau");
		countries.add("Guinea Bissau");
		countries.add("Equatorial Guinea");
		countries.add("El Salvador");
		countries.add("Dominican Republic");
		countries.add("Czech Republic");
		countries.add("Cote d'Ivoire");
		countries.add("Cote d Ivoire");
		countries.add("Costa Rica");
		countries.add("Central African Republic");
		countries.add("Burkina Faso");
		countries.add("Bosnia and Herzegovina");
		countries.add("Antigua and Barbuda");
		/*__------Short Forms--------*/
		countries.add("USA");
		countries.add("UK");
		countries.add("UAE");
		/*__------Short Forms remove ["US".toLowerCase()="us"] --------*/
		//countries.remove("US");

	}

}
